### PR TITLE
Fix the "error loading page" error on login

### LINKED ISSUE #125: Redirect after login error
Hi,
I've tested in BicBucStriim 1.2.4 and 1.2.5a (git) version.

At the login prompt, if i enter the right log/pass combination, i got an error message : 
image
and no redirection...
But, after, i can use all tabs correctly, download epubs... 
It occurs after each login (admin or user) event if the configuration is completed.
For information, i got all green signal at the installation check process.

I'm not blocked but it could mean that the login process has failed for the users... even if it worked...

### LINKED ISSUE #128: "Error Loading Page" after login
## Original Text:

When I try to access my library using chrome on Android (4.4) I am prompted to log in.  I enter valid credentials and I am prompted to enter login again.  Infinite loop.  

Running 1.2.0 on DSM 5 4493 Update 5

Possibly Related...
When I load the page on my desktop, I am able to view books, authors & tags.  I don't remember being prompted for a login, but there is a logout button on the home tab.
I clicked logout and I was prompted to login. I entered valid credentials and got an "Error Loading Page" message. After clicking the books tab, I am able to view the books and I go to the home tab and there is a logout button.
## Update:

Upgraded to 1.2.4
Now I'm seeing the same experience on both mobile and desktop ("Error Loading Page" message, but I am able to view the library)

### PR DESCRIPTION
**Pull request by janeczku**
This bug had been bugging me long enough so i fixed it.
Closes #125 and likely #144 too.

/cc @perler @Pyrosfr @gumaste @badhabits999 @G1zm0

### CODE REVIEW

**Comment by G1zm0** [comment]
Nice!, well done.
:+1:

**Comment by rvolz** [comment]
Ok, one external confirmation. So it will be merged. Thx

**Comment by achandab** [comment]
Im having this issue now. Was working fine until recently. 

Synology NAS 
BBS: 1.3.6-5

Where can i start troubleshooting?

**Comment by rvolz** [comment]
What did you change then? You can always use [debug mode](https://github.com/rvolz/BicBucStriim/wiki/Debug-mode) to look for errors.

**Comment by achandab** [comment]
Has been fixed. Updated software and needed to set the directory again

**Pull request merged**
